source 'https://rubygems.org'

gem 'jekyll-remote-theme'
gem 'jekyll-sitemap'
gem 'jekyll-mentions'
gem 'jekyll-seo-tag'
gem 'jekyll-redirect-from'
gem 'jekyll-default-layout'
gem 'jemoji'
gem 'tzinfo-data'
